#!/usr/bin/env bash

set -e

### configuration ##############################################################

: ${KONG_ADMIN_URL:="http://localhost:8001"}
: ${API_NAME:="mockbin"}
: ${API_URL:="https://mockbin.org"}

### helpers ####################################################################

create_service() {
  curl -i -X POST \
    --url "$KONG_ADMIN_URL/services" \
    --data "name=$API_NAME" \
    --data "url=$API_URL"
}

create_route() {
  curl -i -X POST \
    --url "$KONG_ADMIN_URL/services/$API_NAME/routes" \
    --data "paths[]=/&strip_path=false" \
    --data "protocols[]=https"   # https only allowed for the upstream
}

create_plugin_for_auth() {
  curl -i -X POST \
    --url "$KONG_ADMIN_URL/services/$API_NAME/plugins" \
    --data "name=key-auth"
}

### main #######################################################################

create_service
create_route
create_plugin_for_auth
