#!/usr/bin/env bash

set -e

### configuration ##############################################################

: ${KONG_ADMIN_URL:="http://localhost:8001"}
: ${API_USERNAME:="$(whoami)"}
: ${API_SECRET:=""}  # randomly generated if not set - usually prefer generated

### helpers ####################################################################

create_consumer() {
   curl -i -X PUT \
    --url "$KONG_ADMIN_URL/consumers/$API_USERNAME"
}

create_consumer_secret() {
   curl -i -X PUT \
    --url "$KONG_ADMIN_URL/consumers/$API_USERNAME/key-auth" \
    --data "key=$API_SECRET"
}

### main #######################################################################

create_consumer
create_consumer_secret
