#!/usr/bin/env bash

set -e
set -u

### configuration ##############################################################

: ${API_URL:="https://localhost:8443"}

### main #######################################################################

curl -i -k -X GET \
  --url "$API_URL" \
  --header "apikey: $API_SECRET"
